# Generated by Django 2.0.4 on 2018-04-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180415_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image_test',
            new_name='image',
        ),
    ]
