# Generated by Django 2.0.4 on 2018-04-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
