# Generated by Django 2.0.4 on 2018-04-15 20:45

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=django.utils.datetime_safe.date.today, max_length=100),
            preserve_default=False,
        ),
    ]
