# Generated by Django 2.0.4 on 2018-04-15 20:48

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180415_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.date.today, verbose_name=datetime.date.today),
            preserve_default=False,
        ),
    ]
